# Site settings
title: Andre S. Giron
email: agiron123@gmail.com
description: Made with <3 in Atlanta, GA
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andregiron.me" # the base hostname & protocol for your site
twitter_username: agiron_78
github_username:  agiron123

# Build settings
markdown: kramdown
port: 4001
