name: Jekyll site CI

on:
  push:
    branches: [ "astro-port", "gh-pages" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
  build-astro:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Astro project in a node container
      run: |
        docker run \
        -v ${{ github.workspace }}/astro:/astro \
        -w /astro \
        node:latest /bin/bash -c "npm install && npm run build"